<template>
  <footer text-center flex="~ col items-center" text-sm text-gray-400 dark:text-truegray-600>
    <span text-xs>Site under construction. For preview purposes only.</span>
    <span text-xs>Contains content generated by AI, will be removed in final release.</span>
    <span>© 2003 - Present, LCPU</span>
  </footer>
</template>
